### ISSUE TITLE
Why I can't use  LMIC_enableChannel(10);

### ISSUE THREAD

**Issue by belopezq** [matthijskooijman/arduino-lmic#313]
Greetings
I'm trying to follow a tutorial using this library but when I use  LMIC_enableChannel(10); for setup only channel 10  arduino get one error LMIC_enableChannel was no declarated in this scope, please help me, how I can fix it?

**Comment by matthijskooijman** [comment]
Hi! Did you see that this library is deprecated? You probably want to use another LMIC version (maybe you're already doing this, since a lot of people come here for support while really already using the MCCI version of LMIC...).

In any case, for your particular problem, not that  LMIC_enableChannel is only available for US915, other regions have dynamic channels and use different functions for managing channels. Maybe you are not using US915?
